# These are supported funding model platforms

github: [splax-s]
# patreon: splaxos
# open_collective: splaxos
# ko_fi: splaxos
# tidelift: npm/splax-os
# community_bridge: splax-os
# liberapay: splaxos
# issuehunt: splax-s
# lfx_crowdfunding: splax-os
custom: # ["https://www.buymeacoffee.com/splaxos"]
